name: adriancmurray
favicon: null
layout_spectrum: 0.9261524528264999
typography_spectrum: 0.6498215328902006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.34336246317252517
  lightness: 0.8382571821566671
  saturation: 0.8652062949258834
  rhythmicContrast: 0.8561645271256566
purpose: []
